[package]
name = "kd-tree"
version = "0.1.0"
authors = ["Yuichiro Terada <terada.yuichiro@gmail.com>"]
repository = "https://github.com/u1roh/kd-tree"
keywords = ["kd tree", "kdtree", "k-dimensional tree"]
readme = "README.md"
description = "k-dimensional tree"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
ordered-float = "2.0.0"
pdqselect = "0.1.0"
typenum = "1.12"
paste = "1.0"

[dev-dependencies]
rand = "*"
criterion = "0.3"
fux_kdtree = { version = "0.2.0", package = "fux_kdtree" } 
kdtree = "0.6.0"

[[bench]]
name = "benchmark"
harness = false
