[package]
name = "kd-tree"
version = "0.1.0"
authors = ["Yuichiro Terada <yuichiro_terada@caddi.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test"
path = "bin/test.rs"

[dependencies]
num-traits = "0.2.14"
ordered-float = "2.0.0"
pdqselect = "0.1.0"
typenum = "1.12"
paste = "1.0"

[dev-dependencies]
rand = "*"
criterion = "0.3"
fux_kdtree = { version = "0.2.0", package = "fux_kdtree" } 
kdtree = "0.6.0"

[[bench]]
name = "benchmark"
harness = false
